import { act, fireEvent, render, screen } from "@testing-library/react"
import { afterEach, beforeEach, expect, it, vi } from "vitest"
import OrderPaymentWindow from "./OrderPaymentWindow"
import { ORDER_PAYMENT_REFRESH_EVENT } from "../lib/order-payment"
const order = { databaseId: "order-a", status: "Processing", payment: "gcash", paymentStatus: "pending", paymentExpiresAt: "2026-09-30T03:15:00Z" }
beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime(new Date("2026-09-30T03:00:00Z")); vi.spyOn(navigator, "onLine", "get").mockReturnValue(true) })
afterEach(() => vi.useRealTimers())
it("ticks locally with no network requests and retains the deadline after remount", () => {
  const fetch = vi.spyOn(globalThis, "fetch")
  const first = render(<OrderPaymentWindow order={order} onResume={() => {}} />)
  expect(screen.getByRole("timer").textContent).toBe("15:00")
  act(() => vi.advanceTimersByTime(60_000))
  expect(screen.getByRole("timer").textContent).toBe("14:00")
  first.unmount()
  render(<OrderPaymentWindow order={order} onResume={() => {}} />)
  expect(screen.getByRole("timer").textContent).toBe("14:00")
  expect(fetch).not.toHaveBeenCalled()
})
it("stops ticking in the background and catches up immediately on resume", () => {
  const hidden = vi.spyOn(document, "hidden", "get").mockReturnValue(false)
  render(<OrderPaymentWindow order={order} onResume={() => {}} />)
  hidden.mockReturnValue(true)
  fireEvent(document, new Event("visibilitychange"))
  act(() => vi.advanceTimersByTime(120_000))
  expect(screen.getByRole("timer").textContent).toBe("15:00")
  hidden.mockReturnValue(false)
  fireEvent(document, new Event("visibilitychange"))
  expect(screen.getByRole("timer").textContent).toBe("13:00")
})
it("expires once, stops ticks and requests only one targeted refresh", () => {
  const refresh = vi.fn()
  window.addEventListener(ORDER_PAYMENT_REFRESH_EVENT, refresh)
  render(<OrderPaymentWindow order={order} onResume={() => {}} />)
  act(() => vi.advanceTimersByTime(900_000))
  expect(screen.queryByRole("button", { name: "Continue payment" })).toBeNull()
  expect(screen.getByText("Checking the final status.")).toBeTruthy()
  expect(refresh).toHaveBeenCalledOnce()
  expect(refresh.mock.calls[0][0].detail).toEqual({ orderId: "order-a" })
  act(() => vi.advanceTimersByTime(120_000))
  expect(refresh).toHaveBeenCalledOnce()
  window.removeEventListener(ORDER_PAYMENT_REFRESH_EVENT, refresh)
})
it("removes the timer and action when realtime marks the order paid", () => {
  const view = render(<OrderPaymentWindow order={order} onResume={() => {}} />)
  view.rerender(<OrderPaymentWindow order={{ ...order, paymentStatus: "paid" }} onResume={() => {}} />)
  expect(screen.queryByRole("timer")).toBeNull()
  expect(screen.queryByRole("button")).toBeNull()
})
it("disables payment while offline or opening and makes errors readable", () => {
  const resume = vi.fn()
  const view = render(<OrderPaymentWindow order={order} busy error="Please try again." onResume={resume} />)
  fireEvent.click(screen.getByRole("button"))
  expect(resume).not.toHaveBeenCalled()
  expect(screen.getByRole("alert").textContent).toBe("Please try again.")
  view.rerender(<OrderPaymentWindow order={order} onResume={resume} />)
  vi.spyOn(navigator, "onLine", "get").mockReturnValue(false)
  fireEvent(window, new Event("offline"))
  fireEvent.click(screen.getByRole("button"))
  expect(resume).not.toHaveBeenCalled()
  expect(screen.getByRole("status").textContent).toContain("offline")
})
it("shows final expiry only after server cancellation, never for COD", () => {
  const view = render(<OrderPaymentWindow order={{ ...order, paymentStatus: "failed", status: "Cancelled", cancellationReason: "Payment window expired" }} onResume={() => {}} />)
  expect(screen.getByText("Your reservation has ended.")).toBeTruthy()
  view.rerender(<OrderPaymentWindow order={{ ...order, payment: "cod" }} onResume={() => {}} />)
  expect(screen.queryByLabelText("Order payment window")).toBeNull()
})
